---
title: "Data Dashboard For Data Analyst Jobs"
author: "Selvyn Yovany Martinez Barahona"
date: "5/10/2021"
output: pdf_document
---

```{R,echo = FALSE}
getwd()
```

```{r, warning = FALSE, header = FALSE, message = FALSE, echo=FALSE}
data <- read.csv("2019_data_analyst_job.csv")
install.packages("randomcoloR")                               # Install & load randomcoloR package
library("randomcoloR")
library(tidyverse)
library(pander)
library(reshape2)
library (dplyr)
```

```{r,warning = FALSE, header = FALSE, message = FALSE, echo=FALSE }
job_hired_apply <- data %>% 
     group_by(job_title) %>% # We want info about each level of this variable
     summarize(job_hired = sum(hired == "TRUE", na.rm=TRUE)/7002 *100,
               job_apply = sum(easy_apply == "TRUE")/5340*100) # The info we want


```

```{r echo=TRUE}

colnames(job_hired_apply) <- c("Job_Title",
                               "Percent_Hired", 
                               "Percent_Easy_Apply")

panderOptions('table.split.table', Inf) 
panderOptions('round',2)

pander(job_hired_apply, 

caption = "Percent of Applicants Who Got Hired and Used Easy Apply By Job Title") 
```
```{r}
n <-28
palette <- distinctColorPalette(28)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, header=FALSE}
job_plot <- ggplot(job_hired_apply, aes(x="", y= Percent_Hired, fill=Job_Title)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
  theme_classic()+
  theme_void ()+
  theme(legend.position = "top")+
  scale_fill_manual(values =palette)+
  theme(axis.line = element_blank())+
  theme(axis.text = element_blank())+
  theme(axis.ticks = element_blank())+
  labs(x=NULL, y=NULL, fill=NULL)
  
  
  

job_plot
```
  

``{r, warning = FALSE, header = FALSE, message = FALSE, echo=FALSE}
job_hired_apply <- job_hired_apply %>%
  arrange(job_title) %>%
  mutate(ypos = cumsum(job_hired)-0.5*job_hired)

job_hired_apply %>% mutate_at(vars(job_hired, job_apply, ypos), funs(round(., 2)))

job_hired_apply
```

